task_tracking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasktrack.urls'))
]

tasktrack/urls.py
from django.urls import path
from tasktrack.views import *

urlpatterns = [
    path('', TaskListView.as_view(), name = "task_list"),
    path('<int:pk>/', TaskDetailView.as_view(), name = "task_detail"),
    path('task_add/', TaskAddView.as_view(), name="task_add"),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name = "task_update"),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name = "task_delete"),
    path('comment_add/', CommentAddView.as_view(), name="comment_add"),

]

app_name = "tasktrack"

tasktrack/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    STATUSES= [
        ("notdone", "Not Done"),
        ("in_progress", "In Progress"),
        ("done", "Done")
    ]
    name = models.CharField(max_length = 50)
    description = models.TextField()
    status = models.CharField(max_length = 50, choices = STATUSES, default = "notdone")
    priority = models.IntegerField()
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    start_date = models.DateField()
    dead_line = models.DateField()

    def __str__(self):
        return f"{self.name}"
    
class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

tasktrack/forms.py
from django import forms
from tasktrack.models import Task, Comment

class TaskAdd(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["name", "description", "status", "priority", "start_date", "dead_line", "creator"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

tasktrack/views.py
from django.shortcuts import render
from tasktrack.models import *
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from tasktrack.forms import TaskAdd, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from tasktrack.mixins import *


class TaskListView(ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "tasktrack/task_list.html"

class TaskDetailView(DetailView):
    model = Task
    template_name = "tasktrack/task_detail.html"
    context_object_name = "task"

    #def get_context_data(self, **kwargs)
    #    context = super().get_context_data(**kwargs)
    #    context ["comments"] = Comment.objects.filter(task=self.get_object())
    #    return context

class TaskAddView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasktrack/task_add.html"
    form_class = TaskAdd
    success_url = "/"

class TaskUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Task
    template_name = "tasktrack/task_update.html"
    form_class = TaskAdd
    success_url = "/"

class TaskDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Task
    template_name = "tasktrack/task_delete.html"
    success_url = "/"

class CommentAddView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = "tasktrack/comment_add.html"
    form_class = CommentForm
    success_url = "/"
    
    #def form_valid(self, form):
    #    form.instance.author = self.request.user
    #    form.instance.task = get_object_or_404(Task, pk=self.kwargs.get('pk'))
    #    return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasktrack</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    {% include "header.html" %}
    {% block content %}
    
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><img src="/static/img/logo.jpg" width="35" height="30"></li>
                <li><a href="{% url 'tasktrack:task_list' %}">Головна</a></li>
                <li>{{ user.is_authenticated }}</li>
                <li class="add-task"><a href="{% url 'tasktrack:task_add' %}">Створити нове завдання</a></li>
                <li class="add-comment"><a href="{% url 'tasktrack:comment_add' %}">Створити новий коментар</a></li>
            </ul>
        </nav>
    </header>
</body>
</html>

templates/tasktrack/comment_add.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <form>
            <button type="submit" class="btn btn-primary">Створити</button>
        </form>
    </form>
{% endblock %}

templates/tasktrack/detail.html
{% extends "base.html" %}
{% load static %}

<body>
    {% block content %}
        <h1>Завдання:{{task.name}}</h1>
        <br>
        <h2>{{task.description}}</h2>
        <br>
        <a href="{% url 'task_edit' task_id=task.id %}">
            <button type="submit" class="btn btn-primary">Змінити</button></a>
    {% endblock %}
</body>

templates/tasktrack/task_add.html
{% extends "base.html" %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <form>
            
      
            <button type="submit" class="btn btn-primary">Створити</button>
          </form>
    </form>
{% endblock %}

templates/tasktrack/task_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Оновлення завдання</h2>
    <p>Ви впевнені, що хочете видалити завдання"{{ object.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Оновити завдання</button>
        <a href="{% url 'tasktrack:task_list' %}" class="btn btn-secondary">Назад до списку завдань</a>
    </form>
</div>
{% endblock %}

templates/tasktrack/task_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>{{ task.title }}</h2>
    <p>{{ task.description }}</p>
    <p>Статус: <span class="badge badge-primary">{{ task.status }}</span></p>
    <p>Пріоритет: <span class="badge badge-secondary">{{ task.priority }}</span></p>
    <a href="{% url 'tasktrack:task_update' task.id %}" class="btn btn-warning">Редагувати</a>
    <a href="{% url 'tasktrack:task_delete' task.id %}" class="btn btn-danger">Видалити</a>
</div>

{% endblock %}

templates/tasktrack/task_list.html
{% extends "base.html" %}



<body>
    {% block content %}
    <div class="container mt-3">
        <ul class="list-group">
            {% for task in tasks %}
            <li class="list-group-item">
                <a href="{% url 'tasktrack:task_detail' task.pk %}">{{ task.name }}</a>
                <span class="badge text-bg-primary"> {{ task.status }}</span>
                <span class="badge text-bg-secondary"> Пріоритет: {{ task.priority }}</span>
            </li>
            {% empty %}
            <li class="list-group-item">Завдань не знайдено</li>
            {% endfor %}
        </ul>
    </div>
    {% endblock %}
</body>

templates/tasktrack/task_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Оновлення завдання</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Оновити завдання</button>
        <a href="{% url 'tasktrack:task_list' %}" class="btn btn-secondary">Назад до списку завдань</a>
    </form>
</div>
{% endblock %}